# Generated by Django 5.0.1 on 2024-02-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hdd',
            old_name='firstname',
            new_name='hddname',
        ),
    ]
