# Generated by Django 5.0.1 on 2024-02-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdds', '0003_hdd_hddmemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='hddmemory',
            field=models.IntegerField(default=0),
        ),
    ]
