# Generated by Django 5.0.1 on 2024-02-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdds', '0005_rename_lastname_hdd_hddstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdd',
            name='hdddate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hdd',
            name='hddyear',
            field=models.IntegerField(default=2000),
        ),
    ]
