# Generated by Django 5.0.1 on 2024-02-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdds', '0002_rename_firstname_hdd_hddname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdd',
            name='hddmemory',
            field=models.IntegerField(null=True),
        ),
    ]
