# Generated by Django 5.0.1 on 2024-02-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdds', '0004_alter_hdd_hddmemory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hdd',
            old_name='lastname',
            new_name='hddstatus',
        ),
    ]
